package pt.tecnico.grpc.server;

/* these imported classes are generated by the hello-world-server contract */
import pt.tecnico.grpc.HelloWorld;
import pt.tecnico.grpc.HelloWorldServiceGrpc;

import io.grpc.stub.StreamObserver;

import java.util.List;

public class HelloWorldServiceImpl extends HelloWorldServiceGrpc.HelloWorldServiceImplBase {

	@Override
	public void greeting(HelloWorld.HelloRequest request, StreamObserver<HelloWorld.HelloResponse> responseObserver) {

		// HelloRequest has auto-generated toString method that shows its contents
		System.out.println(request);

		List<String> hobbies = request.getHobbiesList();
		String greeting = request.getName();
		System.out.println("greeting message: " + greeting);
		System.out.println("hobbies:");
		for (String hobby : hobbies) {
			System.out.println(hobby);
		}

		//? Random sleep between 0 and 5000 milliseconds to simulate a long processing time
		try {
			long sleepTime = (long) (Math.random() * 5000);
			System.out.println("Sleeping for " + sleepTime + " milliseconds to simulate processing time...\n");
			Thread.sleep(sleepTime);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		// You must use a builder to construct a new Protobuffer object
		HelloWorld.HelloResponse response = HelloWorld.HelloResponse.newBuilder()
				.setGreeting("Hello " + request.getName()).build();

		// Use responseObserver to send a single response back
		responseObserver.onNext(response);

		// When you are done, you must call onCompleted
		responseObserver.onCompleted();
	}

}
